alias andy='cd ~/Dropbox/Websites/andy-taylor'
alias j='cd ~/Ferocia/johanna'
alias jd='cd ~/Ferocia/johanna-design'
alias ji='cd ~/Ferocia/johanna-ios'
alias fs='foreman start'
alias deploy='sh deploy.sh'
alias dp='sh deploy.sh'