alias andy='cd ~/Dropbox/Websites/andy-taylor'
alias j='cd ~/Ferocia/johanna'
alias f='cd ~/Ferocia/fub'
alias specs='PARALLEL=true script/spec'
alias jd='cd ~/Ferocia/johanna-design'
alias ji='cd ~/Ferocia/johanna-ios'
alias fs='foreman start'
alias fss='FUB_SEED=false foreman start'
alias demo='SEED_SCOPE=demo foreman start'
alias deploy='sh deploy.sh'
alias dp='sh deploy.sh'
alias rubies='ps aux | grep ruby'
alias killrubies="ps aux | grep ruby | grep -v grep | awk '{print $2}' | xargs kill -9"
alias heroku='/usr/bin/heroku'
alias rubby='ruby'
alias gh='ruby ~/.dotfiles/andy/open-in-github.rb'
alias ghp='ruby ~/.dotfiles/andy/open-in-github-pulls.rb'
alias lols='lolcommits --browse'
alias font='fontcustom compile app/assets/images/ferociasans'
alias fubby='git submodule update'
alias search='ack'
alias python-server='python -m SimpleHTTPServer 8000'
alias gdc='git diff | pbcopy'
alias apmu='apm upgrade'
